# Generated by Django 2.2.4 on 2019-09-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='@eis.hokudai.ac.jpのメールアドレスのみ登録できます', max_length=254, unique=True, verbose_name='email'),
        ),
    ]
