# Generated by Django 2.2.4 on 2019-09-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190905_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school_year',
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.TextField(blank=True, max_length=50, verbose_name='grade'),
        ),
    ]
