# Generated by Django 2.2.6 on 2019-12-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190920_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='hokudai.ac.jpのメールアドレスのみ登録できます', max_length=254, unique=True, verbose_name='email'),
        ),
    ]
