# Generated by Django 2.2.4 on 2019-09-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_auto_20190914_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]