# Generated by Django 3.0.2 on 2020-04-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='price',
        ),
    ]
