# Generated by Django 2.2.6 on 2020-04-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_remove_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='choice',
            field=models.CharField(default='どちらでも', max_length=32),
        ),
    ]
