# Generated by Django 2.2.6 on 2020-04-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_offer_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='choice',
        ),
        migrations.AddField(
            model_name='offer',
            name='matching_way',
            field=models.CharField(default='ぜひ会いましょう！', max_length=32),
        ),
    ]
