# Generated by Django 2.2.6 on 2020-04-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_auto_20200428_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='matching_way',
            field=models.CharField(default='チャットメインで！', max_length=32),
        ),
    ]
