# Generated by Django 2.2.6 on 2020-01-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20200107_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='reported_at',
            new_name='created_at',
        ),
    ]
