# Generated by Django 2.2.4 on 2019-09-04 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='offer_apply_user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='offerer',
        ),
        migrations.AddField(
            model_name='chat',
            name='user1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='user2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
