# Generated by Django 2.2.4 on 2019-09-16 20:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_chatunreadtalkcount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatunreadtalkcount',
            unique_together={('user', 'chat')},
        ),
    ]
