# Generated by Django 2.2.6 on 2019-10-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_auto_20190905_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(default='university', max_length=32),
        ),
    ]
