# Generated by Django 3.0.2 on 2020-04-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20200418_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='link',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
